import React from "react";
import "./TermsAndService.scss";

import { useEffect } from "react";

// Particles js Configuration file
import particles from "../../particlesjs-config";

function TermsAndService(props) {
	useEffect(() => {
		tsParticles.load("particles", particles);
	});
	return (
		<>
			<div className="tos">
				<div className="tos__header padding" id="particles">
					<h1 className="tos__header__heading">Terms of Service</h1>
				</div>
				<div className="tos__body padding">
					<p className="document">
						<br />
						<br />
						<span className="bold-head">Data Privacy and Security</span><br /> <br />
						At AIBC, we recognize the paramount importance of safeguarding the privacy and security of our users' data. We have implemented robust measures and protocols to ensure that user information is protected against unauthorized access, disclosure, or alteration. Our adherence to stringent data protection standards is reflected in the contractual agreements we establish with our clients, which delineate the terms governing data collection, processing, storage, and sharing. Our subscription-based model provides clients with greater control over their data and enables them to exercise their rights in accordance with applicable privacy laws and regulations. Additionally, our commitment to transparency is evidenced by our proactive engagement with clients regarding data privacy and security matters, including the provision of regular updates and disclosures on our security practices and compliance initiatives. Should you have any inquiries or require further clarification regarding our data privacy and security policies, please do not hesitate to contact our dedicated support team at aimedia.flow@gmail.com.						<br /> <br />

						<span className="bold-head">User Responsibilities and Limitations</span> <br /> <br />
						While our AI solutions are designed to provide valuable insights and support decision-making processes, users bear the responsibility of exercising prudent judgment and critical thinking in their utilization of the information provided. Furthermore, users are required to adhere to the terms stipulated in their contractual agreements with AIBC, which encompass a range of responsibilities, usage restrictions, and data handling protocols. Compliance with applicable laws and regulations is paramount, and any misuse or unauthorized access to our Services is strictly prohibited. In the event of non-compliance, AIBC reserves the right to take appropriate actions, including but not limited to the suspension or termination of user subscriptions or contracts. Our commitment to maintaining a secure and ethical operating environment is underscored by our adherence to industry best practices and regulatory requirements, ensuring the integrity and confidentiality of user data at all times.
						<br /> <br /> <span className="bold-head">AI-Powered Solutions</span>
						<br /> <br />At AIBC, our commitment to innovation drives us to harness the power of cutting-edge artificial intelligence technologies in developing bespoke solutions tailored to meet the unique challenges and opportunities present in various industries. Through our comprehensive suite of AI-powered products and services, we endeavor to redefine the way businesses operate, empowering them to make informed decisions, optimize processes, and drive sustainable growth. It is imperative to emphasize that the analyses, insights, and recommendations generated by our AI systems are the result of meticulous algorithmic processing and data analysis. These outputs, delivered to our clients under contractual agreements, are characterized by their accuracy, reliability, and actionable nature. Our commitment to quality and excellence is reflected in the contractual terms that govern our engagements, ensuring transparency, accountability, and mutual benefit for all parties involved.<br /> <br />

					</p>
				</div>
			</div>
		</>
	);
}
import "./TermsAndService.scss";

export default TermsAndService;
